import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val junit_ktx: String = "androidx.test.ext:junit-ktx:_"

    const val androidx_test_core: String = "androidx.test:core:_"

    const val androidx_test_runner: String = "androidx.test:runner:_"

    const val aws_android_sdk_s3: String = "com.amazonaws:aws-android-sdk-s3:_"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    const val gson: String = "com.google.code.gson:gson:_"

    const val dagger: String = "com.google.dagger:dagger:_"

    const val dagger_compiler: String = "com.google.dagger:dagger-compiler:_"

    const val mockito_kotlin: String = "com.nhaarman.mockitokotlin2:mockito-kotlin:_"

    const val ktlint: String = "com.pinterest:ktlint:_"

    const val raygun4android: String = "com.raygun:raygun4android:_"

    const val firebase: String = "com.google.firebase:firebase-bom:_"
    const val firebase_crashlytics: String = "com.google.firebase:firebase-crashlytics-ktx"
    const val firebase_analytics: String = "com.google.firebase:firebase-analytics-ktx"
    const val firebase_crashlytics_gradle: String =
        "com.google.firebase:firebase-crashlytics-gradle:_"

    const val moshi: String = "com.squareup.moshi:moshi:_"

    const val moshi_kotlin: String = "com.squareup.moshi:moshi-kotlin:_"

    const val moshi_kotlin_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val android_junit5: String = "de.mannodermaus.gradle.plugins:android-junit5:_"

    const val geojson: String = "io.github.dellisd.spatialk:geojson:_"

    const val ktor_client_android: String = "io.ktor:ktor-client-android:_"

    const val ktor_client_cio: String = "io.ktor:ktor-client-cio:_"

    const val ktor_client_core: String = "io.ktor:ktor-client-core:_"

    const val ktor_client_gson: String = "io.ktor:ktor-client-gson:_"

    const val ktor_client_auth: String = "io.ktor:ktor-client-auth:_"

    const val ktor_client_mock: String = "io.ktor:ktor-client-mock:_"

    const val ktor_client_mock_jvm: String = "io.ktor:ktor-client-mock-jvm:_"

    const val ktor_client_mock_native: String = "io.ktor:ktor-client-mock-native:_"

    const val mockk: String = "io.mockk:mockk:_"

    const val junit: String = "junit:junit:_"

    const val assertj_core: String = "org.assertj:assertj-core:_"

    const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    const val kotlin_parcelize_compiler: String =
            "org.jetbrains.kotlin:kotlin-parcelize-compiler:_"

    const val kotlin_parcelize_runtime: String =
            "org.jetbrains.kotlin:kotlin-parcelize-runtime:_"

    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    const val ktlint_gradle: String = "org.jlleitschuh.gradle:ktlint-gradle:_"

    const val junit_jupiter: String = "org.junit.jupiter:junit-jupiter:_"

    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:_"

    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:_"

    const val junit_jupiter_params: String = "org.junit.jupiter:junit-jupiter-params:_"

    const val junit_vintage_engine: String = "org.junit.vintage:junit-vintage-engine:_"

    const val slf4j_simple: String = "org.slf4j:slf4j-simple:_"
}
